class WindowType():
    WINDOW_FIELD = 0
    WINDOW_START_FIELD = 1
    WINDOW_END_FIELD = 2
    WINDOW_RLIST = 3
    WINDOW_PINFO = 4
    WINDOW_WORKSPACE_LAUNCHER=5
    WINDOW_NEW_PROJECT=6
    WINDOW_DISSECTOR_SCRIPT=7
    WINDOW_PROJECT_IMPORT=8
    WINDOW_PROJECT_EXPORT=9
    WINDOW_ORGANIZE_VIEWS=10
    WINDOW_OPEN_PCAP=11